---
title: "2020 წლის საქართველოს პარლამენტის არჩევნების ამომრჩეველთა აქტივობა"
author: "თემურ გუგუშვილი"
date: '2020-10-31T21:13:14-05:00'
output:
  html_document:
    df_print: paged
  pdf_document: default
tags:
- სტატისტიკა
- არჩევნები
- საპარლამენტო არჩევნები

categories: საპარლამენტო არჩევნები
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

ცენტრალური საარჩევნო კომისიის 2020 წლის საქართველოს პარლამენტის არჩევნების [ამომრჩეველთა აქტივობა](https://cesko.ge/geo/static/2938) შესახებ აქვეყნებს ინფორმაციას. შემდეგი განახლება 17:30 საათზე. 

```{r, include = FALSE}
library(tidyr)
library(tidyverse)
library(ggplot2)
library(readxl)
library(extrafont)
library(cowplot)
library(hrbrthemes)
library(plotly)
library(viridis)
```


```{r, fig.cap='', tidy=FALSE, echo=FALSE, message = FALSE, fig.dim = c(13, 9)}

tg_data_1 <- read_excel("~/Documents/github_project/data/election_2020.xlsx")

tg_p_voting <- ggplot(data=tg_data_1, aes(x=time , y=region, fill =percentage)) +
  geom_tile() +
  theme_gray(base_family="Sylfaen")+
  scale_fill_viridis(discrete=FALSE)+
  theme_ipsum(base_family="Sylfaen") +
  theme(axis.title.x = element_text(colour="black", size=18, hjust=0.5),
        axis.title.y = element_text(colour="black", size=18, hjust=0.5),
        axis.text.x=element_text(angle = 30,  hjust=0.5, size=18, colour="black"),
        axis.text.y=element_text(size=18),
        plot.caption = element_text(size=18, colour="black", hjust=0),
        plot.title=element_text(colour="black", size=20),
        legend.title=element_text(size=18),
        legend.text=element_text(size=18))+
  labs(title = "",
       subtitle ="",
       caption = "წყარო:ცენტრალური საარჩევნო კომისიის (ცესკო)",
       color="")+
  xlab("საათი")+
  ylab("რეგიონი")+
  labs(fill = "ამომრჩეველთა \nაქტიურობა %")+
  
  scale_x_continuous(breaks=seq(10, 12, 2))

tg_p_voting

```
*დიაგრამა 1. ამომრჩეველთა აქტიურობა რეგიონების მიხედვით*

 



 

